# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_collector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x61ta_collector.proto\x12\x0e\x64\x61ta_collector\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xac\x04\n\x08TickData\x12\x12\n\ninstrument\x18\x01 \x01(\t\x12\x14\n\x0cstrike_price\x18\x02 \x01(\x05\x12\x16\n\x0eis_call_option\x18\x03 \x01(\x08\x12\x0e\n\x06ignore\x18\x64 \x01(\t\x12\r\n\x05token\x18\x65 \x01(\t\x12\x16\n\x0e\x62\x65st_buy_price\x18\x66 \x01(\x02\x12\x19\n\x11\x62\x65st_buy_quantity\x18g \x01(\x03\x12\x17\n\x0f\x62\x65st_sell_price\x18h \x01(\x02\x12\x1a\n\x12\x62\x65st_sell_quantity\x18i \x01(\x03\x12\x0b\n\x03ltp\x18j \x01(\x02\x12\x12\n\nprice_high\x18k \x01(\x02\x12\x11\n\tprice_low\x18l \x01(\x02\x12\x17\n\x0fprice_avg_trade\x18m \x01(\x02\x12\x13\n\x0bprice_close\x18n \x01(\x02\x12\x12\n\nprice_open\x18o \x01(\x02\x12 \n\x18price_net_change_percent\x18p \x01(\x02\x12\x15\n\rsell_quantity\x18q \x01(\x03\x12\x14\n\x0c\x62uy_quantity\x18r \x01(\x03\x12\x16\n\x0etrade_quantity\x18s \x01(\x03\x12\x15\n\ropen_interest\x18t \x01(\x03\x12\x19\n\x11total_trade_value\x18u \x01(\x02\x12\x1b\n\x13last_trade_quantity\x18v \x01(\x03\x12\x17\n\x0flast_trade_time\x18w \x01(\t\x12\x12\n\nnet_change\x18x \x01(\x02\"\x0e\n\x0cTickResponse2\xa0\x01\n\x15\x44\x61taCollectionService\x12G\n\x08SayHello\x12\x1c.data_collector.HelloRequest\x1a\x1d.data_collector.HelloResponse\x12>\n\x04Tick\x12\x18.data_collector.TickData\x1a\x1c.data_collector.TickResponseB\x1bZ\x19proto.tick_data_collectorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_collector_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\031proto.tick_data_collector'
  _globals['_HELLOREQUEST']._serialized_start=40
  _globals['_HELLOREQUEST']._serialized_end=68
  _globals['_HELLORESPONSE']._serialized_start=70
  _globals['_HELLORESPONSE']._serialized_end=102
  _globals['_TICKDATA']._serialized_start=105
  _globals['_TICKDATA']._serialized_end=661
  _globals['_TICKRESPONSE']._serialized_start=663
  _globals['_TICKRESPONSE']._serialized_end=677
  _globals['_DATACOLLECTIONSERVICE']._serialized_start=680
  _globals['_DATACOLLECTIONSERVICE']._serialized_end=840
# @@protoc_insertion_point(module_scope)
